#ifndef COMMON_H
#define COMMON_H

#include <QObject>
#include <QColor>

class MyCommon : public QObject
{
    Q_OBJECT

	Q_PROPERTY( QColor COLOR_LIGHT_RED			READ GetCOLOR_LIGHT_RED			CONSTANT )
	Q_PROPERTY( QColor COLOR_RED				READ GetCOLOR_RED				CONSTANT )
	Q_PROPERTY( QColor COLOR_DARK_RED			READ GetCOLOR_DARK_RED			CONSTANT )

	Q_PROPERTY( QColor COLOR_SHIT_YELLOW		READ GetCOLOR_SHIT_YELLOW		CONSTANT )
	Q_PROPERTY( QColor COLOR_SHIT_VIOLET		READ GetCOLOR_SHIT_VIOLET		CONSTANT )

	Q_PROPERTY( QColor COLOR_SELEDIN			READ GetCOLOR_SELEDIN			CONSTANT )
	Q_PROPERTY( QColor COLOR_SELEDIN			READ GetCOLOR_SELEDIN			CONSTANT )

	Q_PROPERTY( QColor COLOR_LIGHT_VIOLET		READ GetCOLOR_LIGHT_VIOLET		CONSTANT )
	Q_PROPERTY( QColor COLOR_VIOLET				READ GetCOLOR_VIOLET			CONSTANT )
	Q_PROPERTY( QColor COLOR_DARK_VIOLET		READ GetCOLOR_DARK_VIOLET		CONSTANT )

	Q_PROPERTY( QColor COLOR_LIGHT_GREEN		READ GetCOLOR_LIGHT_GREEN		CONSTANT )
	Q_PROPERTY( QColor COLOR_GREEN				READ GetCOLOR_GREEN				CONSTANT )
	Q_PROPERTY( QColor COLOR_DARK_GREEN			READ GetCOLOR_DARK_GREEN		CONSTANT )

	Q_PROPERTY( QColor COLOR_LIGHT_BLUE			READ GetCOLOR_LIGHT_BLUE		CONSTANT )
	Q_PROPERTY( QColor COLOR_BLUE				READ GetCOLOR_BLUE				CONSTANT )
	Q_PROPERTY( QColor COLOR_DARK_BLUE			READ GetCOLOR_DARK_BLUE			CONSTANT )

	Q_PROPERTY( QColor COLOR_LIGHT_BLUE			READ GetCOLOR_LIGHT_BLUE		CONSTANT )
	Q_PROPERTY( QColor COLOR_BLUE				READ GetCOLOR_BLUE				CONSTANT )
	Q_PROPERTY( QColor COLOR_DARK_BLUE			READ GetCOLOR_DARK_BLUE			CONSTANT )

	Q_PROPERTY( QColor COLOR_LIGHT_BEIGE		READ GetCOLOR_LIGHT_BEIGE		CONSTANT )
	Q_PROPERTY( QColor COLOR_BEIGE				READ GetCOLOR_BEIGE				CONSTANT )

	Q_PROPERTY( QColor COLOR_LIGHT_GREY			READ GetCOLOR_LIGHT_GREY		CONSTANT )
	Q_PROPERTY( QColor COLOR_GREY				READ GetCOLOR_GREY				CONSTANT )

	Q_PROPERTY( QColor COLOR_LIGHT_KHAKI		READ GetCOLOR_LIGHT_KHAKI		CONSTANT )
	Q_PROPERTY( QColor COLOR_KHAKI				READ GetCOLOR_KHAKI				CONSTANT )

	Q_PROPERTY( QString BTN_START_PRESSED		READ GetBTN_START_PRESSED		CONSTANT )
	Q_PROPERTY( QString BTN_START_RELEASED		READ GetBTN_START_RELEASED		CONSTANT )

	Q_PROPERTY( QString BTN_STOP_PRESSED		READ GetBTN_STOP_PRESSED		CONSTANT )
	Q_PROPERTY( QString BTN_STOP_RELEASED		READ GetBTN_STOP_RELEASED		CONSTANT )

	Q_PROPERTY( QString BTN_BACK_VACUUM_PRESSED		READ GetBTN_BACK_VACUUM_PRESSED		CONSTANT )
	Q_PROPERTY( QString BTN_BACK_VACUUM_RELEASED	READ GetBTN_BACK_VACUUM_RELEASED	CONSTANT )

	Q_PROPERTY( QString FONT_FAMILY_DEFAULT		READ GetFONT_FAMILY_DEFAULT		CONSTANT )

public:
	explicit MyCommon(QObject *parent = 0);

//	enum ConstantValues
//	{
//		SCREEN_WIDTH					= 1280
//		, SCREEN_HEIGHT					= 800
//		, FONT_SIZE_DEFAULT				= 24
//		, FONT_SIZE_BUTTON				= 36
//		, FONT_SIZE_SLIDER_DESCRIPTION	= 36
//		, FONT_SIZE_TITLE				= 36
//		, FONT_SIZE_CONNECTION_TEXT		= 28
//	};
	enum ConstantValues
	{
		SCREEN_WIDTH					= 1024
		, SCREEN_HEIGHT					= 600
		, FONT_SIZE_DEFAULT				= 26
		, FONT_SIZE_BUTTON				= 26
		, FONT_SIZE_SLIDER_DESCRIPTION	= 26
		, FONT_SIZE_TITLE				= 30
		, FONT_SIZE_CONNECTION_TEXT		= 20
	};
	Q_ENUMS( ConstantValues )

	static const QColor COLOR_LIGHT_RED;
	static const QColor COLOR_RED;
	static const QColor COLOR_DARK_RED;

	static const QColor COLOR_SHIT_YELLOW;
	static const QColor COLOR_SHIT_VIOLET;

	static const QColor COLOR_SELEDIN;
	static const QColor COLOR_DARK_SELEDIN;

	static const QColor COLOR_LIGHT_VIOLET;
	static const QColor COLOR_VIOLET;
	static const QColor COLOR_DARK_VIOLET;

	static const QColor COLOR_LIGHT_GREEN;
	static const QColor COLOR_GREEN;
	static const QColor COLOR_DARK_GREEN;

	static const QColor COLOR_LIGHT_BLUE;
	static const QColor COLOR_BLUE;
	static const QColor COLOR_DARK_BLUE;

	static const QColor COLOR_LIGHT_BEIGE;
	static const QColor COLOR_BEIGE;

	static const QColor COLOR_LIGHT_GREY;
	static const QColor COLOR_GREY;

	static const QColor COLOR_LIGHT_KHAKI;
	static const QColor COLOR_KHAKI;

	static const QString BTN_START_PRESSED;
	static const QString BTN_START_RELEASED;

	static const QString BTN_STOP_PRESSED;
	static const QString BTN_STOP_RELEASED;

	static const QString BTN_BACK_VACUUM_PRESSED;
	static const QString BTN_BACK_VACUUM_RELEASED;

	static const QString FONT_FAMILY_DEFAULT;

	QColor GetCOLOR_LIGHT_RED() const;
	QColor GetCOLOR_RED() const;
	QColor GetCOLOR_DARK_RED() const;

	QColor GetCOLOR_SHIT_YELLOW() const;
	QColor GetCOLOR_SHIT_VIOLET() const;

	QColor GetCOLOR_SELEDIN() const;
	QColor GetCOLOR_DARK_SELEDIN() const;

	QColor GetCOLOR_LIGHT_VIOLET() const;
	QColor GetCOLOR_VIOLET() const;
	QColor GetCOLOR_DARK_VIOLET() const;

	QColor GetCOLOR_LIGHT_GREEN() const;
	QColor GetCOLOR_GREEN() const;
	QColor GetCOLOR_DARK_GREEN() const;

	QColor GetCOLOR_LIGHT_BLUE() const;
	QColor GetCOLOR_BLUE() const;
	QColor GetCOLOR_DARK_BLUE() const;

	QColor GetCOLOR_LIGHT_BEIGE() const;
	QColor GetCOLOR_BEIGE() const;

	QColor GetCOLOR_LIGHT_GREY() const;
	QColor GetCOLOR_GREY() const;

	QColor GetCOLOR_LIGHT_KHAKI() const;
	QColor GetCOLOR_KHAKI() const;

	QString GetBTN_START_PRESSED() const;
	QString GetBTN_START_RELEASED() const;

	QString GetBTN_STOP_PRESSED() const;
	QString GetBTN_STOP_RELEASED() const;

	QString GetBTN_BACK_VACUUM_PRESSED() const;
	QString GetBTN_BACK_VACUUM_RELEASED() const;

	QString GetFONT_FAMILY_DEFAULT() const;

	static int GetRandInt(int low, int high);
};

#endif // COMMON_H
